substitutions:
  asset_base_url: ""
  time_timezone: Australia/Sydney
  clock_time_format: "%H:%M"
  clock_date_format: "%a %d/%m"
  home_temperature_entity: sensor.your_temperature
  home_temperature_format: "%.0f°"
  home_humidity_entity: sensor.your_humidity
  home_humidity_format: "%.0f%%"
  home_aqi_entity: sensor.your_aqi
  home_aqi_format: "%.0f"
  home_pressure_entity: sensor.your_pressure
  home_pressure_format: "%.0fhPa"
  home_wind_entity: sensor.your_wind_speed
  home_wind_format: "%.0fkm/h"
  light_entity: light.your_light
  light_page_title: LIGHT
  menu_timer_title: Timer
  menu_fridge_title: Fridge
  light_menu_title: Lights
  thermostat_menu_title: Thermostat
  menu_music_title: Music
  menu_home_title: Home
  light_menu_subtitle: "75%"
  light_rgb_action: script.set_light_rgb
  light_effect_1: "__disabled__"
  light_effect_2: "__disabled__"
  light_effect_3: "__disabled__"
  light_effect_4: "__disabled__"
  light_effect_5: "__disabled__"
  light_effect_6: "__disabled__"
  menu_timer_subtitle: "Auto"
  menu_fridge_subtitle: "Off"
  thermostat_menu_subtitle: "24C"
  menu_music_subtitle: "Off"
  menu_home_subtitle: "Back to Main"
  thermostat_entity: climate.your_ac
  thermostat_target_temperature_attribute: temperature
  thermostat_current_temperature_attribute: current_temperature
  thermostat_current_humidity_attribute: current_humidity
  thermostat_min_temperature_attribute: min_temp
  thermostat_max_temperature_attribute: max_temp
  thermostat_temperature_step_attribute: target_temp_step
  thermostat_min_temperature: "17.0"
  thermostat_max_temperature: "26.0"
  thermostat_temperature_step: "0.5"
  thermostat_temperature_increment: "0.0"

packages:
  external_components: !include src/main/external-components-local.yaml
  hardware:    !include src/main/hardware.yaml
  entities:    !include src/main/entities.yaml
  load_page:   !include src/pages/load.yaml
  clock_page:  !include src/pages/main.yaml
  menu_page:   !include src/pages/menu.yaml
  light_page:  !include src/pages/light.yaml
  air_page:    !include src/pages/air.yaml
  music_page:  !include src/pages/music.yaml
  fridge_page: !include src/pages/fridge.yaml
  timer_page:  !include src/pages/timer.yaml

esphome:
  name: m5stack-dialv1
  friendly_name: M5Stack Dial
  on_boot:
    - priority: 800
      then:
        - switch.turn_on: power_hold
    - priority: -100
      then:
        - pcf8563.read_time:
        - light.turn_on:
            id: display_backlight
            brightness: 100%
        - script.execute: update_loading_page

esp32:
  board: m5stack-stamps3
  variant: esp32s3
  framework:
    type: esp-idf
    sdkconfig_options:
      CONFIG_BROWNOUT_DET: "n"

logger:
  level: INFO

api:
  encryption:
    key: !secret api_encryption_key
  on_client_connected:
    - if:
        condition:
          lambda: 'return (0 == client_info.find("Home Assistant "));'
        then:
          - script.execute: on_ha_connected
  on_client_disconnected:
    - if:
        condition:
          lambda: 'return (0 == client_info.find("Home Assistant "));'
        then:
          - globals.set:
              id: ha_connected
              value: 'false'

ota:
  - platform: esphome
    password: !secret ota_password

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  ap:
    ssid: !secret ap_ssid
    password: !secret ap_password

captive_portal:

globals:
  - id: ha_connected
    type: bool
    initial_value: 'false'

image:
  - file: ${asset_base_url}src/assets/images/logo.png
    id: logo_img
    type: RGB565
    transparency: alpha_channel
    resize: 72x72
  - file: ${asset_base_url}src/assets/images/scene.png
    id: img_scene
    type: RGB565
    transparency: alpha_channel
    resize: 24x24
  - file: ${asset_base_url}src/assets/images/bulb.png
    id: img_light
    type: RGB565
    transparency: alpha_channel
    resize: 24x24
  - file: ${asset_base_url}src/assets/images/ac.png
    id: img_ac
    type: RGB565
    transparency: alpha_channel
    resize: 24x24
  - file: ${asset_base_url}src/assets/images/music.png
    id: img_music
    type: RGB565
    transparency: alpha_channel
    resize: 24x24
  - file: ${asset_base_url}src/assets/images/palette.png
    id: img_palette
    type: RGB565
    transparency: alpha_channel
    resize: 24x24
  - file: ${asset_base_url}src/assets/images/brightness.png
    id: img_brightness
    type: RGB565
    transparency: alpha_channel
    resize: 24x24
  - file: ${asset_base_url}src/assets/images/light.png
    id: img_dengguang
    type: RGB565
    transparency: alpha_channel
    resize: 24x24

color:
  - id: col_bg
    hex: "050812"
  - id: col_text_pri
    hex: "EEF2FF"
  - id: col_text_sec
    hex: "6B7FCC"

lvgl:
  displays:
    - round_display
  touchscreens:
    - touch
  encoders:
    - sensor: encoder
      enter_button: front_button
  buffer_size: "12%"
  color_depth: 16
  bg_color: col_bg
  default_font: font_lbl
